version: "3.8"

services:
  mysql:
    container_name: mysql
    platform: linux/amd64
    image: mysql:8.0.33
    volumes:
      - ./local-db/conf:/etc/mysql/conf.d
      - ./local-db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "23306:3306"
    environment:
      TZ: Asia/Seoul
      MYSQL_ROOT_PASSWORD: 102030
    ulimits:
      nofile:
        soft: 20000
        hard: 40000
    networks:
      - local-net

networks:
  local-net:
    driver: bridge
    external: true
    name: docker_local-net
